version: '3'
services:
  project-svc:
    build:
      context: elysian_project
      dockerfile: dev.Dockerfile
    image: elysian_project
    ports:
      - 3001:8080
    env_file: elysian_project/.env
    links:
      - project-db
      - project-rdb
      - sentinel
    depends_on:
      - project-db
      - project-rdb
      - sentinel
    volumes:
      - $PWD/elysian_project:/app
  project-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - 27017:27017
    volumes:
      - $PWD/dev/data/project_db:/data/db
  project-rdb:
    image: postgres_uuid
    build: pgres-extention
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    volumes:
      - $PWD/dev/data/project_rdb:/var/lib/postgresql/data
