version: '3'
services:
  project-svc:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: elysian_project
    ports:
      - 3001:8080
    links:
      - postgres
      - redis
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
