version: '3'
services:
  project-svc:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: elysian_project
    ports:
      - 3001:8080
    env_file: elysian_project/.env
    links:
      - project-db
      - redis
    depends_on:
      - project-db
      - redis
    volumes:
      - $PWD/elysian_project:/app
  project-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - 27017:27017
    volumes:
      - $PWD/dev/data/project_db:/data/db